### ISSUE TITLE
Unable to Change Password

### ISSUE THREAD

**Issue by daviddotcs** [lad1337/xem#10]
Nothing happens when I attempt to change my password at http://thexem.de/user. I believe this is the fault of the following code within the `changePassword` function in SimpleLoginSecure.php, as `$oneTimeCode` appears to never be assigned.

``` php
$this->CI->db->where('user_activationcode', $oneTimeCode);
$query = $this->CI->db->get_where($this->user_table);
if ($query->num_rows() != 1){
    return false;
}else{
    $user_data = $query->row_array();
    if((int)$user_data['user_id'] != $user_id)
        return false;
}
```

**Comment by thezoggy** [comment]
this has been resolved
