### ISSUE TITLE
Issue with returned data

### ISSUE THREAD

**Issue by srob650** [lad1337/xem#13]
Sorry to post this issue here, but I can't seem to get into the IRC chat (if it still exists).  It seems that there may be an error in the data for the show "Undateable".  http://thexem.de/map/all?id=269618&origin=tvdb
The data for absolute episode 2 is prefaced with "scene_2" instead of "scene" like all the others are, therefore I can't iterate over the dictionary easily.

**Comment by thezoggy** [comment]
its because two scene episodes map to one tvdb ep. visually it make make more sense: http://thexem.de/xem/show/2803

this is not a bug

**Comment by srob650** [comment]
Understood, thanks
