### ISSUE TITLE
CSS not loading on thexem.de

### ISSUE THREAD

**Issue by koper89** [lad1337/xem#9]
Hi, I have a problem with displaying thexem.de Don't know why but it seams that css files are not loading.
Best wishes

**Comment by thezoggy** [comment]
works fine here...

```
>curl -I "http://thexem.de/css/main.css"
HTTP/1.1 200 OK
Date: Tue, 27 May 2014 22:16:05 GMT
Server: Apache/2.2.27 (Unix)
Last-Modified: Sat, 23 Jun 2012 17:08:47 GMT
ETag: "ade79db-4040-4c326cd4705c0"
Accept-Ranges: bytes
Content-Length: 16448
Vary: Accept-Encoding,User-Agent
Access-Control-Allow-Origin: *
Cache-Control: max-age=604800, public
Content-Encoding: compress
Content-Type: text/css
```

**Comment by koper89** [comment]
http://thexem.de/
and it looks ok in your location? because i tried on 2 different browsers and web connections and it still looks like wtihout css

**Comment by thezoggy** [comment]
odd it works fine in firefox..  in chrome/ie the actual js/css is corrupt...
load the url: http://thexem.de/js/main.js / http://thexem.de/css/main.css

if you request the files via curl, they look fine though... so that doens't make me think its a cache issue but a CI problem..

**Comment by thezoggy** [comment]
```
>curl "http://thexem.de/css/main.css"
body {
  background: #eee;
}
.seasonHeader a {
  color: #fff;
  text-decoration: none;
}
table a {
  color: #000;
}
table a:hover {
...
```
